### ISSUE TITLE
Never ending spinning

### ISSUE THREAD

**Issue by eschiendorfer** [wallee-payment/prestashop-1.6#1]
I am using testing your module right now on a thirty bees (prestashop 1.6 fork) installation. I see the payment methods, but when I select them I see a new page with the never ending spinning animation. 

The browser console shows no errors and says: "IFrame has been initialized."

What causes this issue? I am totally in test mode...

My wallee account says: "Der Account ist beschränkt aktiviert. Er wird am 21.01.20 auslaufen." Does this cause it?

**Comment by vttn** [comment]
Please let us know if the issue is till occuring.
